RentMyWrox/Models/Notification.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

using System.ComponentModel.DataAnnotations;

namespace RentMyWrox.Models
{
    public class Notification
    {
        [Key]
        public int Id { get; set; }

        [MaxLength(50)]
        public string Title { get; set; }

        [MaxLength(750)]
        public string Details { get; set; }

        public bool IsAdminOnly { get; set; }

        public DateTime DisplayStartDate { get; set; }

        public DateTime DisplayEndDate { get; set; }

        public DateTime CreateDate { get; set; }
    }
}

RentMyWrox/Models/ShoppingCartSummary.cs
using System.Runtime.Serialization;

namespace RentMyWrox.Models
{
    public class ShoppingCartSummary
    {
        public int Quantity { get; set; }

        public double TotalValue { get; set; }

        public string UserDisplayName { get; set; }
    }
}

RentMyWrox/Controllers/NotificationsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentMyWrox.Models;

namespace RentMyWrox.Controllers
{
    public class NotificationsController : Controller
    {
        [OutputCache(Duration = 3600)]
        public ActionResult AdminSnippet()
        {
            using (RentMyWroxContext context = new RentMyWroxContext())
            {
                Notification note = context.Notifications
                .Where(x => x.DisplayStartDate <= DateTime.Now
                    && x.DisplayEndDate >= DateTime.Now
                    && x.IsAdminOnly)
                .OrderByDescending(x => x.CreateDate)
                .FirstOrDefault();
                return PartialView("_Notification", note);
            }
        }
        
        [OutputCache(Duration = 3600)]
        public ActionResult NonAdminSnippet()
        {
            using (RentMyWroxContext context = new RentMyWroxContext())
            {
                Notification note = context.Notifications
                .Where(x => x.DisplayStartDate <= DateTime.Now
                    && x.DisplayEndDate >= DateTime.Now
                    && !x.IsAdminOnly)
                .OrderByDescending(x => x.CreateDate)
                .FirstOrDefault();
                return PartialView("_Notification", note);
            }
        }
    }
}

RentMyWrox/Controllers/ShoppingCartController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using RentMyWrox.Models;

namespace RentMyWrox.Controllers
{
    public class ShoppingCartController : Controller
    {
        public ActionResult Index()
        {
            using(RentMyWroxContext context = new RentMyWroxContext())
            {
                ShoppingCartSummary summary = GetShoppingCartSummary(context);
                return PartialView("_ShoppingCartSummary", summary);       
            }
        }

        public ActionResult AddToCart(int id)
        {
            Guid UserID = UserHelper.GetUserId();
            using (RentMyWroxContext context = new RentMyWroxContext())
            {
                Item addedItem = context.Items.FirstOrDefault(x => x.Id == id);

                // now that we know it is a valid ID
                if (addedItem != null)
                {
                    // Check to see if this item was already added
                    var sameItemInShoppingCart = context.ShoppingCarts
                         .FirstOrDefault(x => x.Item.Id == id && x.UserId == UserID);
                    if (sameItemInShoppingCart == null)
                    {
                        // if not already in cart then add it
                        ShoppingCart sc = new ShoppingCart
                        {
                            Item = addedItem,
                            UserId = UserID,
                            Quantity = 1,
                            DateAdded = DateTime.Now
                        };
                        context.ShoppingCarts.Add(sc);
                    }
                    else
                    {
                        // increment the quantity of the existing shopping cart item
                        sameItemInShoppingCart.Quantity++;
                    }

                    UserHelper.AddUserVisit(id, context);

                    context.SaveChanges();
                }
                ShoppingCartSummary summary = GetShoppingCartSummary(context);
                return PartialView("_ShoppingCartSummary", summary);
            }
        }

        [Authorize]
        [HttpGet]
        public ActionResult Checkout()
        {
            using (RentMyWroxContext context = new RentMyWroxContext())
            {
                return null;
            }
        }

        private ShoppingCartSummary GetShoppingCartSummary(RentMyWroxContext context)
        {
            Guid UserID = UserHelper.GetUserId();
            ShoppingCartSummary summary = new ShoppingCartSummary();
            var appUser = UserHelper.GetApplicationUser();
            if (appUser != null)
            {
                summary.UserDisplayName = string.Format("{0} {1}", appUser.FirstName, appUser.LastName);
            }

            var cartList = context.ShoppingCarts.Where(x => x.UserId == UserID);
            if (cartList != null && cartList.Count() > 0)
            {
                summary.TotalValue = cartList.Sum(x => x.Quantity * x.Item.Cost);
                summary.Quantity = cartList.Sum(x => x.Quantity);
            }
            return summary;
        }
    }
}

RentMyWrox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

RentMyWrox/Views/Shared/_MVCLayout.cshtml
@using RentMyWrox.Models

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link href="~/Content/RentMyWrox.css" rel="stylesheet" type="text/css" />
    <link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
    <script src="~/Scripts/jquery.unobtrusive-ajax.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/modernizr")    
</head>
<body>
    <div id="header">
        <span id="shoppingcartsummary">@Html.Action("Index", "ShoppingCart")</span>
    </div>
    <div id="nav">
        <div id="LeftNavigation">
            <ul class="level1">
                <li><a href="~/" class="level1">Home</a></li>
                <li><a class="level1" href="~/Contact">Contact Us</a></li>
                <li><a class="level1" href="~/About">About Us</a></li>
                @if (!User.Identity.IsAuthenticated)
                {
                    <li><a class="level1" href="~/Account/Login">Login</a></li>
                }
                else
                {
                    <li>&nbsp;</li>
                }
                @if (User.IsInRole("Admin"))
                {
                    <li><a class="level1" href="/Admin/Default">Admin Home</a></li>
                    <li><a class="level1" href="/Admin/ItemList">Items List</a></li>
                    <li><a class="level1" href="/Admin/OrderList">Order List</a></li>
                    <li><a class="level1" href="/Admin/UserList">User List</a></li>
                }
            </ul>
            <br />
            <div id="storeHoursMessage"></div>
            @Html.Action("NonAdminSnippet", "Notifications")
        </div>
    </div>
    <div id="section">
        @RenderBody()
        <span>
            @if (ConfigManager.ViewNotifications)
            {
                @Html.Action("NonAdminSnippet", "Notifications")
             }
        </span>
    </div>
    <div id="specialnotes">
        @RenderSection("SpecialNotes", false)
    </div>
    <div id="footer">
        footer content here
    </div>
</body>
</html>
@Scripts.Render("~/bundles/common")   
@RenderSection("scripts", required: false)
<script type="text/javascript">
        $(document).ready(function () {
            $(".editordatepicker").datepicker();
        });       
</script>

RentMyWrox/Views/Shared/_Notification.cshtml
@model RentMyWrox.Models.Notification

@if(Model != null)
{
<span class="NotificationTitle">@Model.Title</span>
<span class="NotificationDetail">@Model.Details</span>
}

RentMyWrox/Views/Shared/_RecentItems.cshtml
@model List<RentMyWrox.Models.Item>

@if (Model != null && Model.Count > 0)
{
    <div id="recentItemsTitle">Items you have recently reviewed</div>
    foreach (var item in Model)
    {
        <span class="recentItem">
            <div class="recentItemsName">@item.Name</div>
            <span class="recentItemsDescription">
                @if (item.Description.Length > 250)
                { <span>@item.Description.Substring(0, 250)...</span> }
                else
                { @item.Description }
            </span>
        </span>
    }
}

RentMyWrox/Views/Shared/_ShoppingCartSummary.cshtml
@model RentMyWrox.Models.ShoppingCartSummary
@{
    string display;
}
@if (Model != null && Model.Quantity > 0)
{
    display = string.Format("{0}{1}ou have {2} items in your cart with a value of {3}",
        Model.UserDisplayName,
        string.IsNullOrWhiteSpace(Model.UserDisplayName) ? " Y" : ", y",
        Model.Quantity,
        Model.TotalValue.ToString("C")
        );

    <span>@display</span>
    <a class="checkout" href="\shoppingcart\checkout">Check Out</a>
}
else
{
    display = string.Format("{0}{1}our cart is empty",
       Model.UserDisplayName,
       string.IsNullOrWhiteSpace(Model.UserDisplayName) ? " Y" : ", y"
       );
    <span>@display</span>
}